/*
 * 2022 - Abel Matas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package warehouse.view;

import java.util.ArrayList;
import javax.swing.JSpinner;
import javax.swing.JTable;
import warehouse.model.Location;

/**
 *
 * @author Abel
 */
public class LayoutDialog extends javax.swing.JPanel {

    /**
     * Creates new form LayoutDialog
     */
    public LayoutDialog() {
        initComponents();
    }
    
    public void setModelValues(Integer maxStock, ArrayList<Location> layoutList) {
        jspMaxStock.setValue(maxStock);
        locationDialog1.setModelValues(layoutList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpleDialog1 = new libqew.SimpleDialog();
        jPanel1 = new javax.swing.JPanel();
        lblMaxStock = new javax.swing.JLabel();
        jspMaxStock = new javax.swing.JSpinner();
        locationDialog1 = new warehouse.view.LocationDialog();

        setLayout(new java.awt.BorderLayout());

        simpleDialog1.setLayout(new javax.swing.BoxLayout(simpleDialog1, javax.swing.BoxLayout.LINE_AXIS));

        lblMaxStock.setText("Max Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMaxStock)
                .addGap(48, 48, 48)
                .addComponent(jspMaxStock, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(locationDialog1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxStock)
                    .addComponent(jspMaxStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(locationDialog1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
        );

        simpleDialog1.add(jPanel1);

        add(simpleDialog1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jspMaxStock;
    private javax.swing.JLabel lblMaxStock;
    private warehouse.view.LocationDialog locationDialog1;
    private libqew.SimpleDialog simpleDialog1;
    // End of variables declaration//GEN-END:variables

    public JSpinner getJspMaxStock() {
        return jspMaxStock;
    }

    public JTable getLocationTable() {
        return locationDialog1.getLocationTable();
    }
}
