/*
 * 2022 - Abel Matas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package warehouse.view;

import javax.swing.JTextField;
import libqew.TabDialog;

/**
 *
 * @author Abel
 */
public class OrderTabs extends TabDialog {

    /**
     * Creates new form OrderDetailsDialog
     */
    public OrderTabs() {
        initComponents();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderDetails1 = new warehouse.view.OrderDetailsDialog();
        orderNotes1 = new warehouse.view.OrderNotesDialog();

        orderDetails1.setName("Details"); // NOI18N
        add(orderDetails1, "");

        orderNotes1.setName("Notes"); // NOI18N
        add(orderNotes1, "");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private warehouse.view.OrderDetailsDialog orderDetails1;
    private warehouse.view.OrderNotesDialog orderNotes1;
    // End of variables declaration//GEN-END:variables


    @Override
    public boolean validateThis() {
        System.out.println("+++TRUE+++ORDER DETAILS TabDialog -> libqew.Dialogo.validateThis()");
        return true;
    }    
    
    public void setOrderId(String order) {
        orderDetails1.setOrderId(order);
    }
    
    public JTextField getTxtOrderId() {
        return orderDetails1.getTxtOrderId();
    }

    protected OrderDetailsDialog getOrderDetails() {
        return orderDetails1;
    }
    
   protected OrderNotesDialog getOrderNotesDialog() {
        return orderNotes1;
    }
}
