/*
 * 2022 - Abel Matas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package warehouse.view;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import libqew.SimpleDialog;
import warehouse.model.Location;

/**
 *
 * @author Abel
 */
public class OrderNotesDialog extends SimpleDialog {

    /**
     * Creates new form OrderNotes
     */
    public OrderNotesDialog() {
        initComponents();
        // Para ajustar el tamaño de la tabla
        jTable1.setPreferredScrollableViewportSize(jTable1.getPreferredSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Id Note", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Id Note");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Note");
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean validateThis() {
        System.out.println("+++TRUE+++ORDER NOTES SimpleDialog -> libqew.Dialogo.validateThis()");
        return true;
    }

    protected void setMovelVales(HashMap<Integer, String> orderNotesList) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        // Borra las filas  del DefaultTableModel
        model.setRowCount(0);
        
        for (Map.Entry<Integer, String> entry : orderNotesList.entrySet()) {
            Object key = entry.getKey();
            Object val = entry.getValue();
            
            model.addRow(new Object[]{ key, val });
        }
    }
}
