/*
 * 2022 - Abel Matas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package warehouse.view;

import javax.swing.JTextField;
import libqew.SimpleDialog;

/**
 *
 * @author Abel
 */
public class OrderHeaderDialog extends SimpleDialog {

    /**
     * Creates new form OrderHeader
     */
    public OrderHeaderDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOrderId = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        txtOrderType = new javax.swing.JTextField();
        lblOrderType = new javax.swing.JLabel();
        lblOrderDate = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JTextField();
        lblCloseDate = new javax.swing.JLabel();
        txtCloseDate = new javax.swing.JTextField();
        lblRemarks = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Order"));

        lblOrderId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrderId.setText("Order Id");

        txtOrderId.setText("jTextField1");
        txtOrderId.setName("txtOrderId"); // NOI18N

        txtOrderType.setText("jTextField2");

        lblOrderType.setText("Order Type");

        lblOrderDate.setText("Order Date");

        txtOrderDate.setText("jTextField2");

        lblCloseDate.setText("Close Date");

        txtCloseDate.setText("jTextField2");

        lblRemarks.setText("Remarks");

        txtRemarks.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblOrderDate)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOrderType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOrderDate, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(txtOrderType))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRemarks)
                    .addComponent(lblCloseDate))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCloseDate)
                    .addComponent(txtRemarks))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lblOrderId)
                .addGap(15, 15, 15)
                .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderId)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRemarks)
                            .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCloseDate)
                                .addComponent(txtCloseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOrderDate)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOrderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderType))
                        .addGap(0, 0, 0)
                        .addComponent(txtOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCloseDate;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblOrderType;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JTextField txtCloseDate;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtOrderType;
    private javax.swing.JTextField txtRemarks;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean validateThis() {
        System.out.println("+++TRUE+++ORDER HEADERRRRRR SimpleDialog -> libqew.Dialogo.validateThis()");
        return true;
    }

    public String getCloseDate() {
        return txtCloseDate.getText();
    }

    public void setCloseDate(String closeDate) {
        this.txtCloseDate.setText(closeDate);
    }

    public String getOrderDate() {
        return txtOrderDate.getText();
    }

    public void setOrderDate(String orderDate) {
        this.txtOrderDate.setText(orderDate);
    }

    public String getOrderId() {
        return txtOrderId.getText();
    }

    public void setOrderId(String orderId) {
        this.txtOrderId.setText(orderId);
    }

    public String getOrderType() {
        return txtOrderType.getText();
    }

    public void setOrderType(String orderType) {
        this.txtOrderType.setText(orderType);
    }

    public String getRemarks() {
        return txtRemarks.getText();
    }

    public void setRemarks(String remarks) {
        this.txtRemarks.setText(remarks);
    }

    public JTextField getTxtCloseDate() {
        return txtCloseDate;
    }

    public JTextField getTxtOrderDate() {
        return txtOrderDate;
    }

    public JTextField getTxtOrderId() {
        return txtOrderId;
    }

    public JTextField getTxtOrderType() {
        return txtOrderType;
    }

    public JTextField getTxtRemarks() {
        return txtRemarks;
    }
    
    
}
