/*
 * 2022 - Abel Matas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package warehouse.view;

import javax.swing.JTextField;
import libqew.SimpleDialog;
import warehouse.model.OutboundOrder;

/**
 *
 * @author Abel
 */
public class OutboundOrderDialog extends SimpleDialog {

    /**
     * Creates new form OutboundOrderDialog
     */
    public OutboundOrderDialog() {
        initComponents();
        
        JTextField t1 = orderHeader1.getTxtOrderId();
        JTextField t2 = orderTabs1.getOrderDetails().getTxtOrderId();
        this.addListernerComponents(t2,t1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderHeader1 = new warehouse.view.OrderHeaderDialog();
        orderTabs1 = new warehouse.view.OrderTabs();

        setLayout(new java.awt.BorderLayout());
        add(orderHeader1, java.awt.BorderLayout.NORTH);

        orderTabs1.setLayout(new java.awt.BorderLayout());
        add(orderTabs1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private warehouse.view.OrderHeaderDialog orderHeader1;
    private warehouse.view.OrderTabs orderTabs1;
    // End of variables declaration//GEN-END:variables

    public OrderHeaderDialog getOrderHeader() {
       return orderHeader1;
    }

    public OrderDetailsDialog getOrderDetails() {
        return orderTabs1.getOrderDetails();
    }

    protected OrderTabs getOrderTabs1() {
        return orderTabs1;
    }

    
    protected void setModelValues(OutboundOrder outboundOrder) {
        this.getOrderDetails().setOrderId(outboundOrder.getOrderId());
        this.getOrderDetails().setPostalCode(outboundOrder.getPostalCode());
        this.getOrderDetails().setAddress(outboundOrder.getAddress());
        
        
        this.getOrderTabs1().getOrderNotesDialog().setMovelVales(outboundOrder.getOrderNotes());
        
    }
}
