/*
 * 2022 - Abel Matas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package libqew;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 * Clase Dialogo de tipo árbol
 * @author Abel
 */
public class DialogoArbol extends DialogoExtensible {

    private ArrayList<Component> componentes = new ArrayList<>();

    /**
     * Creates new form DialogoVistaArbol
     */
    public DialogoArbol() {
        super();
        CardLayout layout = new CardLayout();
        super.setLayout(layout);
        initComponents();
        crearArbol();
    }
    

    private void crearArbol() {
        //create the root node
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root");
        //create the child nodes
        DefaultMutableTreeNode Hola1 = new DefaultMutableTreeNode("Hola1");
        DefaultMutableTreeNode Hola2 = new DefaultMutableTreeNode("Hola2");
        //add the child nodes to the root node
        root.add(Hola1);
        root.add(Hola2);
         
        //create the tree by passing in the root node
        add(arbol);
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(root));
        jScrollPaneArbol.setViewportView(arbol);
        
    }

    @Override
    public void agregarComponente(Component componente) {
        componente.setVisible(false);
        componentes.add(componente);
        //jScrollPanel.setViewportView(componente);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPanel = new javax.swing.JSplitPane();
        jScrollPanel = new javax.swing.JScrollPane();
        jScrollPaneArbol = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();

        jSplitPanel.setRightComponent(jScrollPanel);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolValueChanged(evt);
            }
        });
        jScrollPaneArbol.setViewportView(arbol);

        jSplitPanel.setLeftComponent(jScrollPaneArbol);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void arbolValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolValueChanged
        System.out.println(evt.getPath().toString());
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) arbol.getLastSelectedPathComponent();
        System.out.println("Selected Node: " + selectedNode.getUserObject().toString());
       
        for (Component componente : componentes) {     
            String componentName = componente.getName();
            if (componentName!=null) {
                
                if (componentName.equals(selectedNode.getUserObject().toString())) {
                    System.out.println("Component Name: " + componentName);
                    jScrollPanel.setViewportView(componente);
                    ((JPanel)componente).setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_arbolValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JScrollPane jScrollPaneArbol;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JSplitPane jSplitPanel;
    // End of variables declaration//GEN-END:variables
}
